//Auto-generated by RSP Compiler
//Source: test/syntax.rsp.html
library syntax;

import "dart:io";
import "package:stream/stream.dart";

/** Template, syntax, for rendering the view. */
void syntax(HttpConnect connect, {foo, bool detailed:false}) { //9
  final request = connect.request, response = connect.response,
    output = response.outputStream;
  var _ep_;
  response.headers.contentType = new ContentType.fromString("text/html; charset=utf-8");

  output.writeString("""
<!DOCTYPE html>
<html>
  <head>
    <title>"""); //#9

  _ep_ = "$foo.name [${foo.title}]"; //#12
  if (_ep_ != null) output.writeString(_ep_);

  //#12
  output.writeString("""
</title>
  </head>
  <body>
    <p>This is a test with """);
  output.writeString('"""');
  output.writeString("""
.
    <p>Another expresion: """);

  _ep_ = foo.description; //#16
  if (_ep_ != null) output.writeString(_ep_);

  output.writeString("""

    <p>An empty expression: """); //#16

  output.writeString("""

    <p>This is not a tag: [foo ], [another and [/none].
    <ul>
"""); //#18

  output.writeString("""      <li>"""); //#22

  _ep_ = user.name; //#22
  if (_ep_ != null) output.writeString(_ep_);

  output.writeString("""

"""); //#22

  output.writeString("""
      <i>!important!</i>
"""); //#24

  output.writeString("""
      </li>
"""); //#26

  output.writeString("""
    </ul>
  </body>
</html>


"""); //#28
}
