//Auto-generated by RSP Compiler
//Source: test/syntax.rsp.html

/** Template, syntax, for rendering the view. */
void syntax(HttpConnect connect) { //2
  HttpRequest request = connect.request;
  HttpRequest response = connect.response;
  OutputStream output = response.outputStream;

  response.headers.contentType = new ContentType.fromString("text/html; charset=utf-8/");

  output.writeString(""" args="foo, bool detailed:false"]
"""); //#2
  output.writeString("""]
library syntax;
[/dart]
<!DOCTYPE html>
<html>
  <head>
    <title>"""); //#3
  //#9
  output.writeString(""" foo.name ]</title>
  </head>
  <body>
    <p>This is a test with """);
  output.writeString('"""');
  output.writeString(""".
  </body>
</html>

""");
}
