analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
    missing_return: ignore
    body_might_complete_normally_nullable: ignore
    #body_might_complete_normally_catch_error: ignore
linter:
  rules:
    - annotate_overrides
    - avoid_init_to_null
    - camel_case_types
    - constant_identifier_names
    #- unnecessary_new
    #- unnecessary_const
