//Auto-generated by RSP Compiler
//Source: ../forwarderView.rsp.html
part of features;

/// Template, forwarderView, for rendering the view.
Future forwarderView(HttpConnect connect, {bool verified:true}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  if (verified) {

    return connect.forward("/forward");
  } //if

  return null;
}
