//Auto-generated by RSP Compiler
//Source: ../forwarderView.rsp.html
part of features;

/** Template, forwarderView, for rendering the view. */
Future forwarderView(HttpConnect connect) async { //#3
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  if (true) { //if#3

    return connect.forward("/forward"); //forward#4
  } //if

  return null;
}
