//Auto-generated by RSP Compiler
//Source: test/features/fragView.rsp.html
part of features;

/** Template, fragView, for rendering the view. */
void fragView(HttpConnect connect, {Map infos: const {}, header, footer}) { //2
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;
  _e_(v) => v != null ? "$v": ""; _o_(String v) => response.addString(v);

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  if (header != null) { //if#2

    _o_("""  """); //#3

    _o_(_e_(header)); //#3


    _o_("""

"""); //#3
  } //if

  _o_("""
<ul>
  <li>This is a fragment and generated dynamically</li>
"""); //#5

  for (var type in infos.keys) { //for#7

    _o_("""    <li>"""); //#8

    _o_(_e_(type)); //#8


    _o_("""

      <ol>
"""); //#8

    for (var name in infos[type]) { //for#10

      _o_("""        <li>"""); //#11

      _o_(_e_(name)); //#11


      _o_("""
</li>
"""); //#11
    } //for

    _o_("""
      </ol>
    </li>
"""); //#13
  } //for

  _o_("""
</ul>
"""); //#16

  if (footer != null) { //if#17

    _o_("""  """); //#18

    _o_(_e_(footer)); //#18


    _o_("""

"""); //#18
  } //if

  connect.close();
}
