//Auto-generated by RSP Compiler
//Source: test/features/fragView.rsp.html
part of features;

/** Template, fragView, for rendering the view. */
Future fragView(HttpConnect connect, {Map infos: const {}, header, footer}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>(),
  request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");

  if (header != null) { //if#2

    response.write(RSP.nns(header)); //#3


    response.write("""

"""); //#3
  } //if

  response.write("""
<ul>
  <li>This is a fragment and generated dynamically</li>
"""); //#5

  for (var type in infos.keys) { //for#7

    response.write("""    <li>"""); //#8

    response.write(RSP.nns(type)); //#8


    response.write("""

      <ol>
"""); //#8

    for (var name in infos[type]) { //for#10

      response.write("""        <li>"""); //#11

      response.write(RSP.nns(name)); //#11


      response.write("""
</li>
"""); //#11
    } //for

    response.write("""
      </ol>
    </li>
"""); //#13
  } //for

  response.write("""  <li>Browser is """); //#16

  response.write(RSP.nns(connect.browser)); //#16


  response.write("""
</li>
</ul>
"""); //#16

  if (footer != null) { //if#18

    response.write("""  """); //#19

    response.write(RSP.nns(footer)); //#19


    response.write("""

"""); //#19
  } //if

  return RSP.nnf();
}
