//Auto-generated by RSP Compiler
//Source: ../json.rsp.html
part of features;

/** Template, json, for rendering the view. */
Future json(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;
var map = {
  "first": [123, "abc"],
  "second": true
};

  response.write("""

<html>
  <head>
    <title>Test of Json</title>
  </head>
  <body>
""");

  response..write("<script>")..write("foo")..write("=")
   ..write(Rsp.json([map, "another</sCRipt>"]))..writeln('</script>');

  response.write("""    <div id="show"></div>
    <script>
var tests = ["foo[1]", "foo[0].first[0]", "foo[0].second"];
var out = "";
for (var i = 0; i < tests.length; ++i)
  out += tests[i] + ": " + eval(tests[i]) + "<br/>";
document.getElementById("show").innerHTML = out;
    </script>
  </body>
</html>
""");

  return null;
}
