//Auto-generated by RSP Compiler
//Source: ../searchResult.rsp.html
part of features;

/// Template, searchResult, for rendering the view.
Future searchResult(HttpConnect connect, {criteria}) async {
  //ignore: unused_local_variable
  var response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  response.write("""<html>
  <head>
    <title>Search Result</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1>Search Result</h1>
    <p>Criteria:</p>
    <ul>
      <li>text: """);

  response.write(Rsp.nnx(criteria.text));


  response.write("""</li>
      <li>since: """);

  response.write(Rsp.nnx(criteria.since));


  response.write("""</li>
      <li>within: """);

  response.write(Rsp.nnx(criteria.within));


  response.write("""</li>
      <li>hasAttachment: """);

  response.write(Rsp.nnx(criteria.hasAttachment));


  response.write("""</li>
    </ul>
  </body>
</html>
""");

  return null;
}
