//Auto-generated by RSP Compiler
//Source: test/features/searchResult.rsp.html
part of features;

/** Template, searchResult, for rendering the view. */
void searchResult(HttpConnect connect, {criteria}) { //2
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;
  _e_(v) => v != null ? "$v": ""; _o_(String v) => response.addString(v);

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  _o_("""
<html>
  <head>
    <title>Search Result</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1>Search Result</h1>
    <p>Criteria:</p>
    <ul>
      <li>text: """); //#2

  _o_(_e_(criteria.text)); //#11


  _o_("""
</li>
      <li>since: """); //#11

  _o_(_e_(criteria.since)); //#12


  _o_("""
</li>
      <li>within: """); //#12

  _o_(_e_(criteria.within)); //#13


  _o_("""
</li>
      <li>hasAttachment: """); //#13

  _o_(_e_(criteria.hasAttachment)); //#14


  _o_("""
</li>
    </ul>
  </body>
</html>
"""); //#14

  connect.close();
}
