//Auto-generated by RSP Compiler
//Source: example/hello-templating/classic.rsp.html
part of hello_templating;

/** Template, classic, for rendering the view. */
void classic(HttpConnect connect, {header, sidebar, body, footer}) { //2
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  response.write("""
<div>
  <div class="header">
    """); //#2

  response.write(nnstr(header)); //#4


  response.write("""

  </div>
  <div class="sidebar">
    """); //#4

  response.write(nnstr(sidebar)); //#7


  response.write("""

  </div>
  <div class="body">
    """); //#7

  response.write(nnstr(body)); //#10


  response.write("""

  </div>
  <div class="footer">
    """); //#10

  response.write(nnstr(footer)); //#13


  response.write("""

  </div>
</div>
"""); //#13

  connect.close();
}
