//Auto-generated by RSP Compiler
//Source: example/hello-templating/sidebar.rsp.html
part of hello_templating;

/** Template, sidebar, for rendering the view. */
void sidebar(HttpConnect connect) { //2
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  response.write("""
<ul>
  <li>This is a sidebar.</li>
  <li>"""); //#2

  response.write(toNString(new DateTime.now())); //#4


  response.write("""
</li>
</ul>
"""); //#4

  connect.close();
}
