//Auto-generated by RSP Compiler
//Source: example/hello-mvc/webapp/listView.rsp.html
part of hello_mvc;

/** Template, listView, for rendering the view. */
void listView(HttpConnect connect, {String path, List<FileInfo> infos}) { //5
  final request = connect.request, response = connect.response,
    output = response.outputStream;
  var _v_;
  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  output.writeString("""

<!DOCTYPE html>
<html>
  <head>
    <title>Stream: Hello MVC</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1>Directory: """); //#5

  _v_ = path; //#13
  if (_v_ != null) output.writeString("$_v_");

  output.writeString("""
</h2>

    <table border="1px" cellspacing="0">
      <tr>
        <th>Type</th>
        <th>Name</th>
      </tr>
"""); //#13

  for (var info in infos) { //#20

    output.writeString("""

      <tr>
        <td><img src=\""""); //#20

    _v_ = info.isDirectory ? 'file.png': 'directory.png'; //#22
    if (_v_ != null) output.writeString("$_v_");

    output.writeString("""
"/></td>
        <td>"""); //#22

    _v_ = info.name; //#23
    if (_v_ != null) output.writeString("$_v_");

    output.writeString("""
</td>
      </tr>
"""); //#23
  } //for

  output.writeString("""

    </table>

    <ul>
      <li>Please refer to
  <a href="https://github.com/rikulo/stream/tree/master/example/hello-mvc">Github</a> for how it is implemented.</a></li></ul>
  </body>
</html>
"""); //#25

  connect.close();
}
