//Auto-generated by RSP Compiler
//Source: ../listView.rsp.html
part of hello_mvc;

/** Template, listView, for rendering the view. */
Future listView(HttpConnect connect, {String path, List<FileInfo> infos}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>Stream: Hello MVC</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1>Directory: """);

  response.write(Rsp.nnx(path));


  response.write("""</h1>

    <table border="1px" cellspacing="0">
      <tr>
        <th>Type</th>
        <th>Name</th>
      </tr>
""");

  for (var info in infos) {

    response.write("""      <tr>
        <td><img src=\"""");

    response.write(Rsp.nnx(info.isDirectory ? 'file.png': 'directory.png'));


    response.write(""""/></td>
        <td>""");

    response.write(Rsp.nnx(info.name));


    response.write("""</td>
      </tr>
""");
  } //for

  response.write("""    </table>

    <ul>
      <li>Please refer to
  <a href="https://github.com/rikulo/stream/tree/master/example/hello-mvc">Github</a> for how it is implemented.</a></li></ul>
  </body>
</html>
""");

  return null;
}
