//Auto-generated by RSP Compiler
//Source: test/syntax/Issue4.rsp.html
library Issue4_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, Issue4, for rendering the view. */
Future Issue4(HttpConnect connect) { //#1
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = ContentType.parse("""text/html; charset=utf-8""");
var foo = "test";
render(HttpConnect connect, {more, less}) {
}

  response.write("""


abc/"""); //#5

  response.write(RSP.nns(foo)); //#7


  response.write("""

"""); //#7

  return connect.include("""${RSP.nns(foo)}""").then((_) { //#8

    return connect.include("""abc/${RSP.nns(foo)}""").then((_) { //#9

      return RSP.nnf(render(new HttpConnect.chain(connect), more: """abc/${RSP.nns(foo)}""", less: foo)).then((_) { //include#10

        return RSP.nnf();
      }); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
