//Auto-generated by RSP Compiler
//Source: Issue4.rsp.html
library Issue4_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, Issue4, for rendering the view. */
Future Issue4(HttpConnect connect) async { //#1
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;
var foo = "test";
render(HttpConnect connect, {more, less}) {
}

  response.write("""


abc/"""); //#5

  response.write(Rsp.nnx(foo)); //#7


  response.write("""

"""); //#7

  await connect.include("${Rsp.nns(foo)}"); //include#8

  await connect.include("abc/${Rsp.nns(foo)}"); //include#9

  await render(new HttpConnect.chain(connect), more: "abc/${Rsp.nns(foo)}", less: foo); //include#10

  return null;
}
