//Auto-generated by RSP Compiler
//Source: test/syntax/Issue4.rsp.html
library Issue4_rsp;

import 'dart:io';
import 'package:stream/stream.dart';

/** Template, Issue4, for rendering the view. */
void Issue4(HttpConnect connect) { //5
  var _cs_ = new List<HttpConnect>(), request = connect.request, response = connect.response;

  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");
var foo = "test";
void render(HttpConnect connect, {more, less}) {
}

  response.write("""


abc/"""); //#5

  response.write(nnstr(foo)); //#7


  response.write("""

"""); //#7

  connect.include("""${nnstr(foo)}""", success: () { //#8

    connect.include("""abc/${nnstr(foo)}""", success: () { //#9

      render(connect.server.connectForInclusion(connect, success: () { //#10

        connect.close();
      }), more: """abc/${nnstr(foo)}""", less: foo); //end-of-include
    }); //end-of-include
  }); //end-of-include
}
