//Auto-generated by RSP Compiler
//Source: lastModified1.rsp.html
library lastModified1_rsp;

import 'dart:async';
import 'package:stream/stream.dart';


  DateTime lastModified() => DateTime.now();
  String etag() => '1234ab';
  

/// Template, lastModified1, for rendering the view.
Future lastModified1(HttpConnect connect, {input}) async {
  //ignore: unused_local_variable
  var response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8",
  lastModified: lastModified(),
  etag: etag()))
    return null;

  response.write("""<html>
  <head>
    <title></title>
  </head>
  <body>
    """);

  response.write(Rsp.nnx(input.whatever * input.another, encode: 'none', maxLength: 20));


  response.write("""

  </body>
</html>
""");

  return null;
}
