//Auto-generated by RSP Compiler
//Source: lastModified1.rsp.html
library lastModified1_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';


  DateTime lastModified() => new DateTime.now();
  String etag() => '1234ab';
  

/** Template, lastModified1, for rendering the view. */
Future lastModified1(HttpConnect connect, {input}) async { //#7
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8",
  lastModified: lastModified(),
  etag: etag()))
    return null;

  response.write("""<html>
  <head>
    <title></title>
  </head>
  <body>
    """); //#7

  response.write(Rsp.nnx(input.whatever * input.another, encode: 'none', maxLength: 20)); //#12


  response.write("""

  </body>
</html>
"""); //#12

  return null;
}
