//Auto-generated by RSP Compiler
//Source: test/syntax/syntax.rsp.html
library syntax;

import "dart:io";
import "package:stream/stream.dart";

/** Template, syntax, for rendering the view. */
void syntax(HttpConnect connect, {foo, bool c:false}) { //9
  final request = connect.request, response = connect.response;
  var _v_;
  response.headers.contentType = new ContentType.fromString("""${foo.contentType}""");

  response.headers.add("age", """129"""); //#9

  response.headers.add("accept-ranges", foo.acceptRanges); //#9

  response.addString("""
<!DOCTYPE html>
<html>
  <head>
    <title>"""); //#10

  _v_ = "$foo.name [${foo.title}]"; //#13
  if (_v_ != null) response.addString("$_v_");

  //#13
  response.addString("""
</title>
  </head>
  <body>
    <p>This is a test with """);
  response.addString('"""');
  response.addString("""
.
    <p>Another expresion: """);

  _v_ = foo.description; //#17
  if (_v_ != null) response.addString("$_v_");

  response.addString("""

    <p>An empty expression: """); //#17

  response.addString("""

    <p>This is not a tag: [foo ], [another and [/none].
    <ul>
"""); //#19

  for (var user in foo.friends) { //#22

    response.addString("""      <li>"""); //#23

    _v_ = user.name; //#23
    if (_v_ != null) response.addString("$_v_");

    response.addString("""

"""); //#23

    if (user.isCustomer) { //#24

      response.addString("""
      <i>!important!</i>
"""); //#25
    } //if

    while (user.hasMore()) { //#27

      response.addString("""        """); //#28

      _v_ = user.showMore(); //#28
      if (_v_ != null) response.addString("$_v_");

      response.addString("""

"""); //#28
    } //while

    response.addString("""
      </li>
"""); //#30
  } //for

  response.addString("""
    </ul>

"""); //#32

  for (var fruit in ["apple", "orange"]) { //#34
  } //for

  response.addString("""

"""); //#36

  if (foo.isCustomer) { //#37

    response.addString("""
      *Custmer*
"""); //#38

  } else if (c) { //#39

    connect.forward("""/x/y/z"""); //#40
    return;

  } else if (foo.isEmployee) { //#41

    response.addString("""
      *Employee*
"""); //#42

    syntax(connect, c: true, foo: """abc"""); //#43
    return;

  } else { //#44

    response.addString("""
      *Unknown* [/if] 
"""); //#45
  } //if

  response.addString("""
  </body>
</html>


"""); //#47

  connect.close();
}
