//Auto-generated by RSP Compiler
//Source: example/hello-template/webapp/helloView.rsp.html
part of hello_template;

/** Template, helloView, for rendering the view. */
void helloView(HttpConnect connect) { //4
  final request = connect.request, response = connect.response,
    output = response.outputStream;
  var _v_;
  if (!connect.isIncluded)
    response.headers.contentType = new ContentType.fromString("""text/html; charset=utf-8""");

  output.writeString("""

<!DOCTYPE html>
<html>
  <head>
    <title>Stream: Hello Templates</title>
    <link href="theme.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <h1>Stream: Hello Templates</h2>
    <p>Now is """); //#4

  _v_ = new Date.now(); //#13
  if (_v_ != null) output.writeString("$_v_");

  output.writeString("""
.</p>
    <p>This page is served by Rikulo Stream """); //#13

  _v_ = connect.server.version; //#14
  if (_v_ != null) output.writeString("$_v_");

  output.writeString("""
.</p>
    <p>Please refer to
  <a href="https://github.com/rikulo/stream/tree/master/example/hello-template">Github</a> for how it is implemented.</a>
  </body>
</html>
"""); //#14
  if (!connect.isIncluded)
    output.close();
}
