//Auto-generated by RSP Compiler
//Source: example/hello-template/webapp/helloView.rsp.html

//2#
part of hello_template;

/** Template, helloView, for rendering the view. */
void helloView(HttpConnect connect) { //5
}
